Delete documentation/MeetingMinutes directory
camaraproject/Template_API_Repository pull request #4
Opened 2024-04-09 18:13 UTC by wrathwolf

No longer needed as minutes are in the wiki

2024-04-12 12:06 UTC, MarkusKuemmerle requested changes
I would keep the sub directory to leave it open to the Sub Projects what they document in the wiki and what they save in this directory (e.g. slides or other documents)

2024-04-12 12:45 UTC, hdamker commented
> I would keep the sub directory to leave it open to the Sub Projects what they document in the wiki and what they save in this directory (e.g. slides or other documents)

@MarkusKuemmerle This PR is only deleting the "MeetingMinutes" sub directory. "API_Documentation" and even "SupportingDocuments" are still there. For me that looks good - meeting minutes shouldn't be in the repositories going forward.

2024-04-12 12:46 UTC, hdamker approved these changes

2024-04-18 11:56 UTC, MarkusKuemmerle approved these changes
Should be merged together with https://github.com/camaraproject/Governance/pull/125

2024-04-18 12:09 UTC, merged